### PR TITLE
create game component and put in app.js

### PR DESCRIPTION
**Pull request by bencbernstein**

### CODE REVIEW

**Comment by OLI9292** [comment]
I think you should be able to remove the constructor from App.js now

**Comment by OLI9292** [comment]
why the addition of a components dir in addition to views?  seems like we should keep them in the same dir

**Comment by bencbernstein** [comment]
removed constructor

i renamed views directory components ... views dir should be gone

**Comment by OLI9292** [comment]
are we going to use "react-router-native" for routing then cause it's in package.json now?

**Comment by bencbernstein** [comment]
oh sorry, i thought i removed from yarn. i'm not sure, we should discuss, but i think react-navigation will do it

**Pull request merged**
